### PR TITLE
[ENH] Support customized base estimator and predictor

### LINKED ISSUE #29: Generic cascade structure
Maybe at some point, we can refactor and allows user supplying custom models for the layers

### PR DESCRIPTION
**Pull request by xuyxu**
resolves #29 #26

## Steps
* [x] Implement K-Fold wrapper for base estimators
* [x] Implement customized cascade layer
* [x] Implement `set_estimator` and `set_predictor` for the model
* [x] Add unit tests
* [x] Add backward compatibility
* [x] Add documentation and working examples

## Code Snippet

``` python
from deepforest import CascadeForestClassifier

model = CascadeForestClassifier()

# New Steps
estimator_1, estimator_2 = your_estimator(), your_estimator()
model.set_estimator(estimator=[estimator_1, estimator_2],  # a list of your base estimators
                    n_splits=5,  # the number of folds
                    oob_approx=False,  # whether to use out-of-bag approximation
                    random_state=None)  # random state used for base estimators

model.set_predictor(predictor=your_predictor)  # an instantiated object of your predictor

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
```

### CODE REVIEW

**Comment by xuyxu** [comment]
Hi @Maryom, this PR implements the feature request on custom base estimators. If you want to use XGBClassifier as the base estimators, below is the example code:

``` python
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from deepforest import CascadeForestClassifier
from xgboost import XGBClassifier

X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
model = CascadeForestClassifier(random_state=1)

# New Steps
estimators = [XGBClassifier() for _ in range(4)]  # 4 base estimators per cascade layer
model.set_estimators(estimators)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("\nTesting Accuracy: {:.3f} %".format(acc))
```

You can find the wheels for installation [here](https://github.com/LAMDA-NJU/Deep-Forest/actions/runs/627259832) .Feel free to comment below if you have any problem or suggestion when using this feature.

**Review by xuyxu — COMMENTED** [review]
LGTM.

**Comment by Maryom** [comment]
Hi @xuyxu I'm really sorry for not being responsive I was sick. Thank you so much for you awesome work 🙏🏼 it is really handy 👌🏼

**Comment by kangwenhao** [comment]
徐老师，您好！我仿照您的代码段，自定义了xgboost的回归模型，但是一直报错，我有点不知道是为什么？我使用原版深度森林时，没有这样的错误。
image
image

**Comment by kangwenhao** [comment]
下面是正常时的代码
image

**Comment by xuyxu** [comment]
Thanks for reporting @kangwenhao, please refer to #67 for details.

**Comment by kangwenhao** [comment]
Thank you for your help. Good luck!

**Comment by kangwenhao** [comment]
Teacher Xu, hello.Now I can customize one estimator, but if I want to customize two, there will be a problem，
image

**Comment by xuyxu** [comment]
Hi @kangwenhao, please refer to the [API Reference](https://deep-forest.readthedocs.io/en/stable/api_reference.html) for an introduction on `set_estimator`. For example, the name of the first input parameter should be `estimators` instead of `estimator`.

**Pull request merged**
