### PR TITLE
fix: reshape array for CascadeForestRegressor in customized mode

### PR DESCRIPTION
**Pull request by xuyxu**
* [x] fix the problem
* [x] improve the coverage of unit tests

### CODE REVIEW

**Comment by xuyxu** [comment]
cc @kangwenhao.

Thanks for reporting! This is a problem due to the inconsistency on the array shape of predictors. For example, for univariate regression, the prediction of some predictors (e.g., XGBRegressor) is an array of shape `(n_samples,)`, wheras that of other predictors could be an array of shape `(n_samples, 1)`.

In this PR, we have added additional operations to unify the array shape under different cases.

**Comment by kangwenhao** [comment]
Thank you for your help. But I'm Xiaobai. I don't know how to put the place you repaired in the library of my computer?

**Comment by kangwenhao** [comment]
Thank you for your help. Good luck!

**Comment by xuyxu** [comment]
Please follow the steps below, and let me know if you have any problem:

* Uninstall the current version: `pip uninstall deep-forest`
* Download the wheels built in this PR: [ZIP](https://github.com/LAMDA-NJU/Deep-Forest/suites/2471378139/artifacts/53145513)
* Select the appropriate wheel according to your platform and Python version
* Open a terminal and switch it into the folder that contains the wheel
* run `pip install XXXX.whl`

**Review by xuyxu — COMMENTED** [review]
LGTM.

**Pull request merged**
