### PR TITLE
添加`CascadeForestClassifier`类对`cross_val_score`交叉验证的支持。

### PR DESCRIPTION
**Pull request by pjgao**
给`BaseCascadeForest`添加基类`BaseEstimator`以包含`get_params`方法; 对`CascadeForestClassifier`添加`ClassifierMixin`基类以包含`score`方法。

Related Issue: #2

### CODE REVIEW

**Comment by xuyxu** [comment]
Hi @pjgao, thanks for the PR! It looks like there is a problem on flake8 formatting, you can check the logs from the CI: Code-Quality for details.

**Comment by xuyxu** [comment]
Great! I will have a final check tomorrow, and merge it if there is no problem ;-) 

Once again, thanks for the PR!

**Comment by xuyxu** [comment]
Hi @pjgao, I have made some edits on your code:
* Sync with the master branch
* Re-write the `__init__` for `CascadeForestClassifier` to make `get_params()` and `set_params()` actually work

Let me know if you are OK with these changes ;-) I will merge this PR if you have no problem.

**Comment by pjgao** [comment]
It looks great, now we can use <tab> to autocomplete the params.

**Pull request merged**
